# Generated by Django 4.2.9 on 2024-04-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-04-04'),
            preserve_default=False,
        ),
    ]
